//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParlanceNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public int ReceipentID { get; set; }
        public bool IsFriend { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime EditedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
